%% ASEN 6116 - Computational Investigation Assignment  
% Author: Rebecca Blum
% Group 7
% Purpose: This script serves as a wrapper script for running all our 
%   simulations. The script calls setup_algae.m to start each V-HAB 
%   simulation and runs oLastSimObj.plot to save the desired data vectors 
%   to the simulation xls file. 

%% Parameters:
% Below are the parameters that we are investigating. It is important to 
%   note that the photobioreactor volume is calculated by multiplying the 
%   coefficient by the number of crew members. 

% 1: Photobioreactor volume coefficient [0.05, 0.06, 0.07]..............m^2
% 2: # of crew members (affects dissolved CO concentration) [2, 4, 6]
% 3: Light intensity [100, 200, 300]...............................µmol/m2s
% 4: Light color ["RedExperimental", "Daylight", "Green"] 

%% Loop through simulations
% First we used the L9 Taguchi matrix to identify unstable parameter 
%   combinations. Then a larger, refined matrix based on the stable 
%   simulations is used to perform a sensitivity analysis on the 
%   parameters. Both matrices vary the three levels of each parameter. 

for i = 3:3  
    % L9 Taguchi matrix  
    %.         1  2  3  4...............parameter number (as defined above)
%     L9 = [1, 1, 1, 1, 1; ...           
%           2, 1, 2, 2, 2; ...
%           3, 1, 3, 3, 3; ...
%           4, 2, 1, 2, 3; ...
%           5, 2, 2, 3, 1; ...
%           6, 2, 3, 1, 2; ...
%           7, 3, 1, 3, 2; ...
%           8, 3, 2, 1, 3; ...
%           9, 3, 3, 2, 1];

    % Parameter sensitivity matrix 
    L9 = [1, 1, 1, 1, 1; ...
          2, 1, 2, 1, 1; ...
          3, 1, 1, 2, 1; ...
          4, 1, 1, 1, 2; ...
          5, 1, 3, 1, 1; ...
          6, 1, 1, 3, 1; ...
          7, 1, 1, 1, 3; ...
          8, 1, 2, 2, 2; ...
          9, 1, 3, 2, 2; ...
          10, 1, 2, 3, 2; ...
          11, 1, 2, 2, 3; ...
          12, 1, 1, 2, 2; ...
          13, 1, 2, 1, 2; ...
          14, 1, 2, 2, 1; ...
          15, 1, 3, 3, 3; ...
          16, 2, 1, 1, 1; ...
          17, 3, 1, 1, 1; ...
          18, 2, 2, 2, 2; ...
          19, 2, 3, 2, 2; ...
          20, 2, 1, 2, 2];

	% Write simulation combination to text file (this is read into the 
    %   PhotobioreactorTutorial so it knows what combination to use for 
    %   each simulation)
    root = "C:\Users\Rebecca Blum\OneDrive - UCB-O365\Desktop\Spacecraft Life Support Systems\Newer V-HAB\V-HAB-main\user\+blbe\+introduction\";
    filename = root + "parameters.txt";
	line = L9(i,:);
    writematrix(line,filename)

	% Execute vhab simulation
    vhab.exec('blbe.introduction.setup_algae_safe')
    
    % Log values to xls file 
    oLastSimObj.plot
end 

fprintf("\nSimulations complete :) \n\n")